CREATE SCHEMA IF NOT EXISTS blogs;

CREATE SCHEMA IF NOT EXISTS news;

CREATE SCHEMA IF NOT EXISTS user;

CREATE TABLE news.news (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);