[alias]
createsuperuser = "run --bin createsuperuser --"
dbshell = "run --bin dbshell --"
inspectdb = "run --bin inspectdb --"
makemigrations = "run --bin makemigrations --"
migrate = "run --bin migrate --"
shell = "run --bin shell --"
showmigrations = "run --bin showmigrations --"
squashmigrations = "run --bin squashmigrations --"
startapp = "run --bin startapp --"
tests = "run --bin tests --"
